//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailwayReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime Dob { get; set; }
        public string Email { get; set; }
        public int ContactNo { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string User_Type { get; set; }
    }
}
